### ISSUE TITLE
[joss-reviews#2974] Annotation errors

### ISSUE THREAD

**Issue by chkoar** [moead-framework/framework#45]
Related: openjournals/joss-reviews#2974

As I can see type annotations are not used. For some code there are type annotations though. Here are some of the errors found.

```python
moead_framework/solution/one_dimension_solution.py:9: error: Need type annotation for 'solution' (hint: "solution: List[<type>] = ...")
moead_framework/solution/one_dimension_solution.py:10: error: Need type annotation for 'F' (hint: "F: List[<type>] = ...")
moead_framework/tool/result.py:67: error: Bracketed expression "[...]" is not valid as a type
moead_framework/tool/result.py:67: note: Did you mean "List[...]"?
moead_framework/tool/result.py:69: error: Incompatible types in assignment (expression has type "List[<nothing>]", variable has type "MultiList")
moead_framework/tool/result.py:71: error: Function "numpy.array" is not valid as a type
moead_framework/tool/result.py:71: note: Perhaps you need "Callable[...]" or a callback protocol?
moead_framework/tool/result.py:86: error: np.array? has no attribute "__iter__" (not iterable)
```

**Comment by geoffreyp** [comment]
Can you give me the command line to get this error list ?

**Comment by chkoar** [comment]
`mypy`

**Comment by geoffreyp** [comment]
it is fixed with the PR https://github.com/moead-framework/framework/pull/46

**Comment by chkoar** [comment]
It is not fixed. 
```
moead_framework/solution/one_dimension_solution.py:9: error: Need type annotation for 'decision_vector' (hint: "decision_vector: List[<type>] = ...")
moead_framework/solution/one_dimension_solution.py:10: error: Need type annotation for 'F' (hint: "F: List[<type>] = ...")
moead_framework/tool/result.py:67: error: Bracketed expression "[...]" is not valid as a type
moead_framework/tool/result.py:67: note: Did you mean "List[...]"?
moead_framework/tool/result.py:69: error: Incompatible types in assignment (expression has type "List[<nothing>]", variable has type "MultiList")
moead_framework/tool/result.py:71: error: Function "numpy.array" is not valid as a type
moead_framework/tool/result.py:71: note: Perhaps you need "Callable[...]" or a callback protocol?
moead_framework/tool/result.py:86: error: np.array? has no attribute "__iter__" (not iterable)
moead_framework/problem/combinatorial/rmnk.py:13: error: Incompatible types in assignment (expression has type "Type[int]", base class "Problem" defined the type as "Type[float]")
moead_framework/problem/combinatorial/mubqp.py:13: error: Incompatible types in assignment (expression has type "Type[int]", base class "Problem" defined the type as "Type[float]")
```

I propose to avoid the use of types if you are not familiar. Provide enough docstrings and it will be enough currently.

**Comment by geoffreyp** [comment]
> I propose to avoid the use of types if you are not familiar. Provide enough docstrings and it will be enough currently.

what do I need to add in the docstring ? Can you give me an example here ?

**Comment by chkoar** [comment]
> Thank you for the example, but what do I need to add in my documentation ?

As long as you keep your documentation in good coverage probably you will be ok without annotations.
Although, having annotations is a good thing for several reasons.

The following problems remain.

```
moead_framework/solution/one_dimension_solution.py:9: error: Need type annotation for 'decision_vector' (hint: "decision_vector: List[<type>] = ...")
moead_framework/solution/one_dimension_solution.py:10: error: Need type annotation for 'F' (hint: "F: List[<type>] = ...")
moead_framework/tool/result.py:82: error: Bracketed expression "[...]" is not valid as a type
moead_framework/tool/result.py:82: note: Did you mean "List[...]"?
moead_framework/tool/result.py:84: error: Incompatible types in assignment (expression has type "List[<nothing>]", variable has type "MultiList")
moead_framework/tool/result.py:86: error: Function "numpy.array" is not valid as a type
moead_framework/tool/result.py:86: note: Perhaps you need "Callable[...]" or a callback protocol?
moead_framework/tool/result.py:101: error: np.array? has no attribute "__iter__" (not iterable)
moead_framework/problem/problem.py:44: error: Argument 1 to "array" has incompatible type "Union[Solution, Sequence[Any]]"; expected "Union[List[Any], List[List[Any]], List[List[List[Any]]], List[List[List[List[Any]]]], Iterable[ndarray[Any]], ndarray[Any]]"
moead_framework/problem/combinatorial/rmnk.py:13: error: Incompatible types in assignment (expression has type "Type[int]", base class "Problem" defined the type as "Type[float]")
moead_framework/problem/combinatorial/mubqp.py:13: error: Incompatible types in assignment (expression has type "Type[int]", base class "Problem" defined the type as "Type[float]")
Found 9 errors in 5 files (checked 71 source files)
```

**Comment by geoffreyp** [comment]
It seems to be solved in https://github.com/moead-framework/framework/pull/75. 
I only have errors on my side with numpy stubs

```
(framework-dev) ➜  framework git:(issue-45-error-annotation) ✗ mypy moead_framework
moead_framework/tool/mop.py:2: error: Skipping analyzing 'numpy': found module but no type hints or library stubs
moead_framework/core/genetic_operator/combinatorial/crossover.py:2: error: Skipping analyzing 'numpy': found module but no type hints or library stubs
moead_framework/problem/problem.py:4: error: Skipping analyzing 'numpy': found module but no type hints or library stubs
moead_framework/core/genetic_operator/numerical/moead_de_operators.py:2: error: Skipping analyzing 'numpy': found module but no type hints or library stubs
moead_framework/algorithm/abstract_moead.py:3: error: Skipping analyzing 'numpy': found module but no type hints or library stubs
moead_framework/problem/numerical/zdt.py:1: error: Skipping analyzing 'numpy': found module but no type hints or library stubs
moead_framework/problem/combinatorial/rmnk.py:1: error: Skipping analyzing 'numpy': found module but no type hints or library stubs
moead_framework/problem/combinatorial/mubqp.py:1: error: Skipping analyzing 'numpy': found module but no type hints or library stubs
moead_framework/problem/combinatorial/knapsack.py:1: error: Skipping analyzing 'numpy': found module but no type hints or library stubs
moead_framework/tool/result.py:3: error: Skipping analyzing 'numpy': found module but no type hints or library stubs
moead_framework/algorithm/combinatorial/moead_dra.py:1: error: Skipping analyzing 'numpy': found module but no type hints or library stubs
moead_framework/algorithm/combinatorial/moead_dra.py:1: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports
Found 11 errors in 11 files (checked 71 source files)

```

**Comment by chkoar** [comment]
> It seems to be solved in #75.

Yes, it does.
